export const INIT_BAIDU_CLIENT = 'INIT_BAIDU_CLIENT'
export const INIT_BAIDU_CLIENT_RES = 'INIT_BAIDU_CLIENT_RES'
export const BAIDU_TTS_START = 'INIT_BAIDU_TTS'
export const BAIDU_TTS_START_RES = 'INIT_BAIDU_TTS_RES'
